### PR TITLE
Minimize qemu initialization

### PR DESCRIPTION
**Pull request by StefanScherer**
Remove duplicate steps.

### CODE REVIEW

**Comment by StefanScherer** [comment]
@philipz FYI, this is [the only additional step](https://github.com/hypriot/rpi-mysql/blob/e7dd5c5b60bbded9f762d2ab20fc43b229bf2dec/.travis.yml#L7) needed to build ARM Docker images on Travis. I've played with your CircleCI approach and the blog post from Resin, but now found this one-liner.

**Comment by philipz** [comment]
@StefanScherer, thank you! This multiarch/qemu-user-static approach is really better than Resin example.

**Comment by philipz** [comment]
Hi @StefanScherer, I have try this method on CircleCI, but it's not work. I guess TravisCI and CircleCI use different techniques, maybe because of the building environment.
https://circleci.com/gh/philipz/docker-arm-circleci/20#config/containers/0

**Comment by StefanScherer** [comment]
@philipz I started on Circle with your repo, then tried the Resin approach. After several hours after switching to Travis I stripped down the changes to this single line. Travis uses VMs for Docker service where you can use this feature. Circle only has lxc-docker, but there is a private beta with hopefully better docker support.

**Comment by philipz** [comment]
@StefanScherer I was tried this rpi-myql on CircleCI. The building is no problem, only the testing 'mysql --version' is failed, because the ENTRYPOINT executes before QEMU-STATIC-ARM. So ARM on CircleCI is not a general purpose.
https://circleci.com/gh/philipz/docker-arm-circleci/30

**Pull request merged**
